var annotated =
[
    [ "fr.redbilled.pcscforjava.ATR", "classfr_1_1redbilled_1_1pcscforjava_1_1_a_t_r.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_a_t_r" ],
    [ "fr.redbilled.pcscforjava.Card", "classfr_1_1redbilled_1_1pcscforjava_1_1_card.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_card" ],
    [ "fr.redbilled.pcscforjava.CardChannel", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_channel.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_channel" ],
    [ "fr.redbilled.pcscforjava.CardException", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_exception.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_exception" ],
    [ "fr.redbilled.pcscforjava.CardNotPresentException", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_not_present_exception.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_not_present_exception" ],
    [ "fr.redbilled.pcscforjava.CardPermission", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_permission.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_permission" ],
    [ "fr.redbilled.pcscforjava.CardTerminal", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_terminal.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_terminal" ],
    [ "fr.redbilled.pcscforjava.CardTerminals", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_terminals.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_card_terminals" ],
    [ "fr.redbilled.pcscforjava.CardTerminalsEvent", "interfacefr_1_1redbilled_1_1pcscforjava_1_1_card_terminals_event.html", "interfacefr_1_1redbilled_1_1pcscforjava_1_1_card_terminals_event" ],
    [ "fr.redbilled.pcscforjava.CommandAPDU", "classfr_1_1redbilled_1_1pcscforjava_1_1_command_a_p_d_u.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_command_a_p_d_u" ],
    [ "JavaVM_", "struct_java_v_m__.html", "struct_java_v_m__" ],
    [ "JavaVMAttachArgs", "struct_java_v_m_attach_args.html", "struct_java_v_m_attach_args" ],
    [ "JavaVMInitArgs", "struct_java_v_m_init_args.html", "struct_java_v_m_init_args" ],
    [ "JavaVMOption", "struct_java_v_m_option.html", "struct_java_v_m_option" ],
    [ "JNIEnv_", "struct_j_n_i_env__.html", "struct_j_n_i_env__" ],
    [ "JNIInvokeInterface_", "struct_j_n_i_invoke_interface__.html", "struct_j_n_i_invoke_interface__" ],
    [ "JNINativeInterface_", "struct_j_n_i_native_interface__.html", "struct_j_n_i_native_interface__" ],
    [ "JNINativeMethod", "struct_j_n_i_native_method.html", "struct_j_n_i_native_method" ],
    [ "jvalue", "unionjvalue.html", "unionjvalue" ],
    [ "fr.redbilled.pcscforjava.NewMain", "classfr_1_1redbilled_1_1pcscforjava_1_1_new_main.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_new_main" ],
    [ "fr.redbilled.security.pcscforjava.PCSC4Java", "classfr_1_1redbilled_1_1security_1_1pcscforjava_1_1_p_c_s_c4_java.html", "classfr_1_1redbilled_1_1security_1_1pcscforjava_1_1_p_c_s_c4_java" ],
    [ "fr.redbilled.security.pcscforjava.PCSCDefines", "classfr_1_1redbilled_1_1security_1_1pcscforjava_1_1_p_c_s_c_defines.html", null ],
    [ "fr.redbilled.pcscforjava.PCSCDefines", "classfr_1_1redbilled_1_1pcscforjava_1_1_p_c_s_c_defines.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_p_c_s_c_defines" ],
    [ "fr.redbilled.security.pcscforjava.PCSCPnPThread", "classfr_1_1redbilled_1_1security_1_1pcscforjava_1_1_p_c_s_c_pn_p_thread.html", "classfr_1_1redbilled_1_1security_1_1pcscforjava_1_1_p_c_s_c_pn_p_thread" ],
    [ "fr.redbilled.pcscforjava.PCSCResource", "classfr_1_1redbilled_1_1pcscforjava_1_1_p_c_s_c_resource.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_p_c_s_c_resource" ],
    [ "fr.redbilled.pcscforjava.ResponseAPDU", "classfr_1_1redbilled_1_1pcscforjava_1_1_response_a_p_d_u.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_response_a_p_d_u" ],
    [ "fr.redbilled.pcscforjava.TerminalFactory", "classfr_1_1redbilled_1_1pcscforjava_1_1_terminal_factory.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_terminal_factory" ],
    [ "fr.redbilled.pcscforjava.TerminalFactorySpi", "classfr_1_1redbilled_1_1pcscforjava_1_1_terminal_factory_spi.html", "classfr_1_1redbilled_1_1pcscforjava_1_1_terminal_factory_spi" ]
];